### ISSUE TITLE
GameSettings render distance extension conflict

### ISSUE THREAD

**Issue by MagmaBro123** [FalsePattern/FalseTweaks#141]
Title.

Downgrading FalseTweaks, Lumina, FalsePatternLib, and ChunkAPI by 2 or so versions fixes this.

[crash-2023-11-20_16.25.52-client.txt](https://github.com/FalsePattern/FalseTweaks/files/13420297/crash-2023-11-20_16.25.52-client.txt)
[fml-client-latest.log](https://github.com/FalsePattern/FalseTweaks/files/13420300/fml-client-latest.log)

Crash report has listed mods.

Reported this to Embedded, he says this is on your end, by the way.

![image](https://github.com/FalsePattern/FalseTweaks/assets/51277766/6f823b75-5070-45d6-a809-ee34d172a2f8)

**Comment by FalsePattern** [comment]
Ah, this is irrelevant to archaicfix, it's another patch conflicting with a different mod.
Add these command line arguments: `-Dlegacy.debugClassLoading=true -Dlegacy.debugClassLoadingSave=true` and then run the game without FalseTweaks, make sure to open video settings so that all the relevant classes load.

After that, turn off the game, and send over this file from .minecraft: `CLASSLOADER_TEMP/net/minecraft/client/settings/GameSettings.class`

If there are multiple CLASSLOADER_TEMP folders, send the class file from the one with the highest number.

**Comment by MagmaBro123** [comment]
GitHub and Dropbox hate class folders, so I can't send this over.

**Comment by FalsePattern** [comment]
Ah, it's a conflict with ArchaicFix's raiseMaxRenderDistance feature

**Comment by MagmaBro123** [comment]
Just noticed pre03. Is this fixed?

**Comment by FalsePattern** [comment]
Yep
