### ISSUE TITLE
Crashes with optifine D6 on loading world?

### ISSUE THREAD

**Issue by MathiusXII** [FalsePattern/FalseTweaks#205]
[crash-2024-12-07_19.32.52-client.txt](https://github.com/user-attachments/files/18050334/crash-2024-12-07_19.32.52-client.txt)

Only mods loaded are
FalsePatternLib v1.5.4
FalseTweaks v3.6.2
Optifine vD6
Unimixins v0.1.19

mipmapFix is false too

**Comment by huihiuhuai** [comment]
try Optifine E7

**Comment by MathiusXII** [comment]
That worked.
Thanks!
I updated falsetweaks to 3.7.3 btw

**Comment by FalsePattern** [comment]
Fixed in 3.7.6

**Comment by Sylvestial** [comment]
I'm not sure if this issue is fixed or I need to enable a setting but Optifine D6 still crashes when paired with FalseTweaks. The only mods I am using are +unimixins-all-1.7.10-0.1.20, falsepatternlib-mc1.7.10-1.5.10, falsetweaks-mc1.7.10-3.9.0, OptiFine_1.7.10_HD_U_D6.

Here's the crash report:

[crash-2025-04-30_20.55.21-client.txt](https://github.com/user-attachments/files/19987096/crash-2025-04-30_20.55.21-client.txt)
