### ISSUE TITLE
The game crashed

### ISSUE THREAD

**Issue by Omgise** [FalsePattern/FalseTweaks#30]
[crash-2022-08-31_09.21.47-client.txt](https://github.com/FalsePattern/Triangulator/files/9457589/crash-2022-08-31_09.21.47-client.txt)
I used optifine.

**Comment by FalsePattern** [comment]
Both Neodymium, Triangulator, and OptiFine do some pretty invasive tweaks to the renderer, you might be seeing a 3-way conflict here.

I'm already working on Triangulator 2.X, so this probably won't be fixed in 1.X, seeing as how it would require a pretty deep modification to code that's already being rewritten anyways.

**Comment by FalsePattern** [comment]
neodymium+triangulator should be fixed in 2.0 alpha 1

**Comment by FalsePattern** [comment]
Delete SpongeMixins and replace it with GasStation: https://github.com/FalsePattern/GasStation.
I no longer support SpongeMixins in my mods.

**Comment by quentin452** [comment]
delete mixingasm is in gastation

**Comment by FalsePattern** [comment]
Also, make sure to rename the OptiFine jar to `OptiFine_1.7.10_HD_U_E7.jar`.
If the optifine jar is not in the mods folder with the proper name format, then triangulator won't work with it.

**Comment by quentin452** [comment]
calibrate it

**Comment by FalsePattern** [comment]
Click on the message, it will show two images, click the `TOGGLE` button until the two squares have the same shape, then click the `APPLY`

**Comment by FalsePattern** [comment]
yes. If you click on `APPLY` when they're like this, the lighting fix will work correctly.
