### ISSUE TITLE
Crash at startup [FT alpha5]

### ISSUE THREAD

**Issue by tyrael93** [FalsePattern/FalseTweaks#49]
Just updated FTweaks to alpha5, with FPLib .10.11 and GStation 0.3.5, the game crashes at startup citing a critical injection failure and slew of other errors. The error doesn't present itself with alpha4.

https://mclo.gs/aAcZNiW

**Comment by FalsePattern** [comment]
Disable the startup uptimizations module in the config under the `00_modules` category.

**Comment by tyrael93** [comment]
Oh, I had already disabled that, since I had had issues with it before. I'm guessing I have to disable the texture optimization module?
![Screenshot from 2022-09-30 09-27-23](https://user-images.githubusercontent.com/5557920/193215209-331fb763-4403-4f72-b461-a551f89f58ce.png)

**Comment by FalsePattern** [comment]
> Oh, I had already disabled that, since I had had issues with it before. I'm guessing I have to disable the texture optimization module? ![Screenshot from 2022-09-30 09-27-23](https://user-images.githubusercontent.com/5557920/193215209-331fb763-4403-4f72-b461-a551f89f58ce.png)

your config is corrupted because you didn't delete the falsetweaks.cfg file before updating to alpha 5, it clearly says in huge bold text.
Delete it and try disabling the startup optimizations again after letting the file regenerate.

![Screenshot_2022-09-30_09-30-01](https://user-images.githubusercontent.com/30945458/193215686-fa931216-df8c-4c1a-bc93-f6ac987cf247.png)

**Comment by tyrael93** [comment]
lol
lmao even
