### ISSUE TITLE
Textures flickering in PFAA Geologica with Triangulator enabled

### ISSUE THREAD

**Issue by Crimento** [FalsePattern/FalseTweaks#71]
Blocks from [PFAA:Geologica](https://github.com/lawremi/PerFabricaAdAstra) have flickering textures when using the mod with FalseTweaks. I only noticed this recently because it only appears with modified blocks like cobble or bricks (raw stones are not affected). 

Modlist:

- GasStation 0.4.0
- FalsePatternLib 0.10.13
- FalseTweaks 2.0 Beta 3
- PFAA-0.2.30

Disabling Triangulator module removes the issues. Disabling **FIX_BLOCK_CRACK** didn't help.

**Comment by brandyyn** [comment]
after installing falsetweaks there are glitchy overlapping textures with artifice ores
https://i.imgur.com/MC83mF2.png

**Comment by brandyyn** [comment]
disabling ENABLE_QUAD_TRIANGULATION doesn't fix it, disabling triangulator module does fix it. I have Neodymium installed if that's relevant, also this didn't happen when I was using triangulator standalone (version: triangulator-mc1.7.10-1.7.3), and i'm on falsetweaks-mc1.7.10-2.0.0-beta0003

**Comment by FalsePattern** [comment]
Works in the latest version when BOTH the crack fix and the quad triangulation are disabled.

**Comment by brandyyn** [comment]
no matter what combinations i've tried in the config looking at artifice ores(for example iron in basalt) through ice or water the ore part of the texture will glitch. i tested without falsetweaks and it still happens, so this isn't a fault of falsetweaks but i was wondering if it could possibly fix it? 
![image](https://user-images.githubusercontent.com/11356565/209327268-a9ef7fb9-f983-46dc-a231-e250d077d618.png)

**Comment by FalsePattern** [comment]
> no matter what combinations i've tried in the config looking at artifice ores(for example iron in basalt) through ice or water the ore part of the texture will glitch. i tested without falsetweaks and it still happens, so this isn't a fault of falsetweaks but i was wondering if it could possibly fix it? ![image](https://user-images.githubusercontent.com/11356565/209327268-a9ef7fb9-f983-46dc-a231-e250d077d618.png)

Fixing this would need a full rewrite of the render engine, so no

**Comment by brandyyn** [comment]
false, like i said previously, 

> after installing falsetweaks there are glitchy overlapping textures with artifice ores https://i.imgur.com/MC83mF2.png


> disabling ENABLE_QUAD_TRIANGULATION doesn't fix it, disabling triangulator module does fix it. I have Neodymium installed if that's relevant, also this didn't happen when I was using triangulator standalone (version: triangulator-mc1.7.10-1.7.3), and i'm on falsetweaks-mc1.7.10-2.0.0-beta0003

this wasn't an issue when i was using triangulator



> no matter what combinations i've tried in the config looking at artifice ores(for example iron in basalt) through ice or water the ore part of the texture will glitch. i tested without falsetweaks and it still happens, so this isn't a fault of falsetweaks but i was wondering if it could possibly fix it? ![image](https://user-images.githubusercontent.com/11356565/209327268-a9ef7fb9-f983-46dc-a231-e250d077d618.png)

this was a different issue that you can ignore, it was caused by another mod and it's been fixed

but that first issue, the one we both reported on originally is a thing. unless you don't plan to fix that, but i guess that's okay too? I'm not sure.

**Comment by Crimento** [comment]
@brandyyn why did you put this here initially? Create another issue and mention this one as related.

@FalsePattern  this probably confused you. Is there a way to fix this on the mod side then while keeping quad triangulation enabled? I linked the source of PFAA in the initial post, the mod is abandoned

**Comment by FalsePattern** [comment]
Fixing the translucent overlay bug with the current render system will cause #25 to reappear.

**Comment by brandyyn** [comment]
> @brandyyn why did you put this here initially? Create another issue and mention this one as related.

I thought it would be a related fix, my bad.

Quad triangulation and block crack fix dont do much or improve performance and you still get ambient occlusion with it disabled so this isn’t a big deal

**Comment by brandyyn** [comment]
is there any chance htis can be looked at again? @FalsePattern 

I am suffering with the tradeoff between my ores flickering and my game having white dots everywhere from the block crack fix being disabled, either way my game has a glaring ugly-ness to it. 

Block crack fix does this to my ores 
![image](https://github.com/FalsePattern/FalseTweaks/assets/11356565/8b90c4be-c46d-4613-a70d-8b355017a669)

but with it disabled my game looks like this:
![image](https://github.com/FalsePattern/FalseTweaks/assets/11356565/182807be-7c89-4efe-8c29-f74cc30d8532)
and its way uglier while playing than in a screenshot because those dots jump around and shimmer and multiple show at once on each different frame :(
